{{- if .Values.piholeAdminPass }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "pihole-synchronized.fullname" . }}-secret
type: Opaque
stringData:
    webpassword: {{ .Values.piholeAdminPass }}
{{- end }}