apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole-synchronized.fullname" . }}-http
spec:
  ports:
    - port: 80
      name: http
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "pihole-synchronized.fullname" . }}-0  # Only expose first pod for the web-ui
