apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole-synchronized.fullname" . }}
  labels:
    {{- include "pihole-synchronized.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
    - port: 53
      targetPort: 53
      protocol: TCP
      name: port53
    - port: 53
      targetPort: 53
      protocol: UDP
      name: port53-udp
    - port: 67
      targetPort: 67
      protocol: UDP
      name: port67-udp
  clusterIP: None
  selector:
    {{- include "pihole-synchronized.selectorLabels" . | nindent 4 }}
