apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole-synchronized.fullname" . }}-udp
  annotations:
    metallb.universe.tf/address-pool: {{ .Values.loadBalancer.addressPool }}
    metallb.universe.tf/allow-shared-ip: {{ .Values.loadBalancer.sharedIpKey }}
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.loadBalancer.ip }}
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: port53-udp
    - port: 67
      targetPort: 67
      protocol: UDP
      name: port67-udp
  selector:
    {{- include "pihole-synchronized.selectorLabels" . | nindent 4 }}
  type: LoadBalancer
