apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: statefulset-scale
  name: {{ include "pihole-synchronized.fullname" . }}-statefulset-scale
subjects:
- kind: ServiceAccount
  name: {{ include "pihole-synchronized.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "pihole-synchronized.fullname" . }}-syncer
  apiGroup: rbac.authorization.k8s.io
