{{- if not .Values.ingress.tlsSecret and  .Values.ingress.cert and .Values.ingress.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pihole-synchronized.fullname" . }}-tls
stringData:
{{- with .Values.ingress.cert }}
  tls.crt: |
  {{- toString . | nindent 4 }}
{{- end }}

{{- with .Values.ingress.key }}
  tls.key: |
  {{- toString . | nindent 4 }}
{{- end }}
type: kubernetes.io/tls
{{- end -}}