name: Helm PR Checks
on:
  pull_request:
    branch: [ main ]
    paths:
      - 'pihole-synchronized/**'

jobs:
  helms-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v1

      - name: Lint pihole-synchronized
        run: helm lint pihole-synchronized

      - name: Install bump2version
        run: pip install bump2version

      - name: Get current version
        id: current-version
        run: echo "::set-output name=version::$(bump2version --list --dry-run patch | grep current_version= | sed -r s,"^.*=",,)"

      - name: Checkout ${{ github.base_ref }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}

      - name: Get ${{ github.base_ref }} version
        id: old-version
        run: |
          echo "::set-output name=version::$(bump2version --dry-run --list --allow-dirty patch | grep current_version= | sed -r s,"^.*=",,)"

      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Check version has been bumped
        run: "python .github/workflows/version_compare.py --current-branch ${{ steps.current-version.outputs.version }} --target-branch ${{ steps.old-version.outputs.version }}"