name: pihole-sync-image Build and Push

on:
  pull_request:
    paths:
      - 'pihole-sync-image/**'

jobs:
  python-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dev dependencies
        run: pip install -r pihole-sync-image/dev_requirements.txt

      - name: Check Black formatting has been applied
        run: black --check pihole-sync-image/pihole_sync.py