name: PR Checks
on:
  pull_request:
    branch: [ main ]

jobs:
  python-pr:
    runs-on: ubuntu-latest
    env:
      working_dir: "pihole-sync-image"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dev dependencies
        run: pip install -r dev_requirements.txt
        working-directory: ${{ env.working_dir }}

      - name: Check Black formatting has been applied
        run: black --check pihole_sync.py
        working-directory: ${{ env.working_dir }}

      - name: Check pylint passes
        run: pylint pihole_sync.py
        working-directory: ${{ env.working_dir }}